### ISSUE TITLE
Accept also IPv6 version of hexadecimal IPv4 notation

### ISSUE THREAD

**Issue by gnanet** [C-REMO/Deobscure-IP-Deobfuscator#1]
This (found in wordfence logs) version notates an ipv4 encapsulated in an ipv6 notation:
00000000000000000000ffff4532c450

if the **00000000000000000000ffff** is replaced by **0x** one is getting **0x4532c450** which can already be resolved by your script:
```

./IP-Deobfuscator.py --ip 0x4532c450

IP Deobfuscator   #v0.1f
  Author: Omer Ramić <@sp_omer>

[~] Deobfuscated IP:

[+] 69.50.196.80

```

You could maybe check for this case too.

**Comment by C-REMO** [comment]
Thanks man, I wasn't considering ipv4 mapped addresses into ipv6. I have added these cases as well.
Your ip is stripped, there are no delimiters (:). But added that case as well.

Now working with this values of ipv4 mapped addresses to ipv6:
0:0:0:0:0:ffff:4532:c450
::ffff:69.50.196.80
::ffff:4532:c450
0000:0000:0000:0000:0000:ffff:4532:c450
00000:00000:00000:00000:00000:65535:17714:50256
00000000000000000000ffff4532c450

Thanks!

**Comment by findneo** [comment]
Some IP addresses generated by [my little script](https://github.com/findneo/IP-Obfuscator) can be parsed by "Ping.exe" but seem not to  be well deobfuscated. I have tried to look into the code but made little progress :)
Here is my test script:
```python
import obscureIP     # my script is named obscureIP.py
import IPDeobfuscator   #your tool is named IPDeobfuscator.py
wtf = []
for i in obscureIP.res:
    try:
        IPDeobfuscator.obscured_ip(i)
    except Exception as e:
        wtf.append(i)
print '\n\n', wtf,'\n',len(wtf), "ip are not Deobfuscated"
``` 
and here is part of the output:
```python
['0x000000c0.0xa8.0x00000000042e9', '0x000000000c0.0x000000000a8.000000041351', '0x00000000c0.168.0x042e9', '0x00c0.168.0000041351', '0x000000c0.000000250.0x000000042e9', '0x000000c0.0000000000250.00000000041351', '192.0x000000a8.0x0042e9', '192.0x00000a8.000000041351', '192.168.0x42e9', '192.168.00000041351', '192.0000000250.0x000000042e9', '192.00000250.041351', '0000000300.0xa8.0x42e9', '000300.0x00a8.00000000041351', '00000000300.168.0x0000042e9', '000300.168.0000000041351', '0000000000300.0250.0x000000042e9', '000300.00250.041351', '0x00000c0.0x0000000a842e9', '0x00000c0.000000000052041351', '192.0x00a842e9', '192.00052041351', '0300.0x00a842e9', '0000300.000000052041351'] 
24 ip are not Deobfuscated
```

**Comment by C-REMO** [comment]
Thank you findneo for bringing it to my attention, it was silly error :) ... I have fixed it. It now works for all the values you provided me.
